version: '3'

services:
  web:
    container_name: th-text-to-date
    image: looksorn/date
    networks:
      - webnet
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
networks:
  webnet: