version: '3'
services:
  chatbot:
    container_name: chatbot
    image: looksorn/chatbot
    restart: always
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.1"
    #       memory: 50M
    #   restart_policy:
    #     condition: on-failure
    build: .
    # volumes:
    #   - .:/usr/src/app/
    ports:
      - "1337:1337"
    networks:
      - webnet
    links:
      - mongo
    depends_on:
      - mongo
    stop_signal: SIGINT
  mongo:
    container_name: mongo
    image: mongo
    command: --smallfiles
    ports:
      - "27017:27017"
    networks:
      - webnet
    # volumes:
    #   - ./.data:/data/db
  date:
    container_name: th-text-to-date
    build:
      context: ../django2
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - webnet
networks:
  webnet: